language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install --user codecov && codecov -t CODECLIMATE_REPO_TOKEN
# command to run tests
script:
  - python manage.py run_test #pip setup.py install
  - python manage.py cover
after_success:
  - codecov