language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install nose
# command to run tests
script:
  - python manage.py run_test #pip setup.py install
  - nosetests --with-coverage
after_success:
  - coveralls