language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script:
  - python manage.py run_test #pip setup.py install
  - python manage.py cover
after_script:
  - codeclimate-test-reporter

after_success:
  - coveralls