language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - python manage.py run_test #pip setup.py install
  - python manage.py cover
after_success:
  - coveralls